using System.Text;
using Verso.Abstractions;
using Verso.Export;

namespace Verso.Tests.Export;

[TestClass]
public sealed class NotebookHtmlExporterTests
{
    [TestMethod]
    public void Export_EmptyNotebook_ProducesValidHtmlStructure()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<!DOCTYPE html>"));
        Assert.IsTrue(html.Contains("<html lang=\"en\">"));
        Assert.IsTrue(html.Contains("</html>"));
        Assert.IsTrue(html.Contains("<head>"));
        Assert.IsTrue(html.Contains("<body>"));
        Assert.IsTrue(html.Contains("Generated by Verso"));
    }

    [TestMethod]
    public void Export_WithTitle_TitleAppearsInTitleTagAndH1()
    {
        var html = ExportToString("My Notebook", Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<title>My Notebook</title>"));
        Assert.IsTrue(html.Contains("<h1>My Notebook</h1>"));
    }

    [TestMethod]
    public void Export_NullTitle_FallsBackToVersoNotebook()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<title>Verso Notebook</title>"));
        Assert.IsTrue(html.Contains("<h1>Verso Notebook</h1>"));
    }

    [TestMethod]
    public void Export_MarkdownCell_RenderedViaMarkdig()
    {
        var cells = new[]
        {
            new CellModel { Type = "markdown", Source = "# Heading" }
        };

        var html = ExportToString(null, cells, null);

        // Markdig with UseAdvancedExtensions may add id attributes to headings
        Assert.IsTrue(html.Contains("<h1") && html.Contains("Heading</h1>"));
    }

    [TestMethod]
    public void Export_CodeCell_SourceInPreCode()
    {
        var cells = new[]
        {
            new CellModel { Type = "code", Language = "csharp", Source = "Console.WriteLine(\"hello\");" }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("<pre><code>"));
        Assert.IsTrue(html.Contains("Console.WriteLine(&quot;hello&quot;);"));
        Assert.IsTrue(html.Contains("csharp"));
    }

    [TestMethod]
    public void Export_TextPlainOutput_RenderedInOutputText()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/plain", "Hello World") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("verso-output--text"));
        Assert.IsTrue(html.Contains("Hello World"));
    }

    [TestMethod]
    public void Export_HtmlOutput_RawEmbed()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/html", "<div>Custom</div>") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("<div>Custom</div>"));
        Assert.IsTrue(html.Contains("verso-output--html"));
    }

    [TestMethod]
    public void Export_ErrorOutput_RenderedWithErrorClass()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/plain", "Something failed", IsError: true, ErrorName: "RuntimeError", ErrorStackTrace: "at Main()") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("verso-output--error"));
        Assert.IsTrue(html.Contains("RuntimeError"));
        Assert.IsTrue(html.Contains("Something failed"));
        Assert.IsTrue(html.Contains("at Main()"));
    }

    [TestMethod]
    public void Export_ImagePngOutput_RenderedAsDataUri()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("image/png", "iVBORw0KGgo=") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("data:image/png;base64,iVBORw0KGgo="));
    }

    [TestMethod]
    public void Export_WithTheme_CssVariablesEmbedded()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        // Should contain CSS variables from default theme tokens
        Assert.IsTrue(html.Contains(":root {"));
        Assert.IsTrue(html.Contains("--verso-"));
    }

    [TestMethod]
    public void Export_TitleWithHtmlChars_IsEscaped()
    {
        var html = ExportToString("<script>alert('xss')</script>", Array.Empty<CellModel>(), null);

        Assert.IsFalse(html.Contains("<script>alert"));
        Assert.IsTrue(html.Contains("&lt;script&gt;"));
    }

    private static string ExportToString(string? title, IReadOnlyList<CellModel> cells, ITheme? theme)
    {
        var bytes = NotebookHtmlExporter.Export(title, cells, theme);
        return Encoding.UTF8.GetString(bytes);
    }
}
